### ISSUE TITLE
Support setting innerHTML on Client

### ISSUE THREAD

**Issue by austinsheep** [chinedufn/percy#117]
When a string of HTML is inserted into a view, only the server renders the HTML properly.  The client will display the string of HTML with escaped characters, showing the HTML tags as text.

This can be easily replicated by inserting `{ "<strong>test</strong>" }` into the output of some view's render function.  It would be nice to have the client render such strings similarly by setting `innerHTML`.

**Comment by chinedufn** [comment]
Thanks for opening this issue!!

Implemented in https://github.com/chinedufn/percy/pull/118

Mind giving it a review then I'll get it merged and deployed in a new virtual-dom-rs version?

**Comment by austinsheep** [comment]
Looks great!
