### ISSUE TITLE
Rust keywords in attribute list

### ISSUE THREAD

**Issue by FinnStokes** [chinedufn/percy#130]
When compiling a HTML form containing `label`s with `for` attributes, I get the error
```
error: expected `>`
  --> app/src/views/login.rs:18:24
   |
18 |                 <label for="username">Username:</label>
   |                        ^^^

error: aborting due to previous error
```

My current workaround is to use capitalisation to avoid the parser treating the attribute as a keyword (since Rust is case sensitive and HTML is not). For example:
```
<label For="username">Username:</label>
```

There are four [Rust keywords](https://doc.rust-lang.org/reference/keywords.html) that are also [valid HTML attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes): `async`, `for`, `loop`, and `type`. There already seems to be special handling for `type` in `parse_attributes`:  https://github.com/chinedufn/percy/blob/66e1dcd4ed94733160ec694dfcb2021be3d7503a/crates/html-macro/src/tag.rs#L131-L144

I think the remaining three keywords just need to be added there. I will create a pull request for this change.

**Comment by chinedufn** [comment]
Thanks for opening this very thorough issue!
