### ISSUE TITLE
The book, readme and vids don't really explain Percy to traditional serverside devs

### ISSUE THREAD

**Issue by simbo1905** [chinedufn/percy#132]
Hello 👋 

I stumbled on the “rust belt rust” video and it took me a while to get the big picture of what Percy is. The video was engaging enough for me to really want to ”get it” and so led me here. I wanted to make a tiny contribution of suggesting to add an ”explain it to me like I am five” below the strap line of “it is Rust + WebAssembly and Isomorphic”. 

To attempt to justify my suggestion many traditional serverside devs are only a bit aware of isomorphic concepts, virtual dom and that rust compiles to wasm. If they dont know one if those things they may totally miss the “holy shit this is really cool!” moment of Percy. 

I don’t know exactly what the correct paragraph is but something like:

“Percy is modular toolkit for building single page web apps entirely in Rust that can also be rendered at the server. This males Percy apps search engine friendly while also having apps that run as high performance WebAssembly within the browser. You get all the performance and safety of Rust on both the client and the server using a consistent virtual DOM programming model.”

Or maybe I still don't get it but you can just correct me and post it as the first paragraph of the book, the readme, and on the first slide of any presentations.

Thanks for the ”holy shit that is really cool” moment!

**Comment by chinedufn** [comment]
Hey!

This is awesome, awesome feedback - thanks so much for providing an example!

I've taken a stab at adding a bit more context as to what Percy is for here - 6d74e85

Does that help? How can it be improved? Also - always feel free to submit a PR since you have some really neat ideas around better communicating this stuff!

Thank you!

**Comment by simbo1905** [comment]
Great!
