### ISSUE TITLE
Define isomorphic

### ISSUE THREAD

**Issue by alexreg** [chinedufn/percy#15]
It has a very specific mathematical and chemical meaning, but clearly neither applies here. Most readers will have no clue what you're talking about, so I think it needs definition.

**Comment by qm3ster** [comment]
Everyone knows exactly what that means.
It means that code written once runs on both the client and the server.
Most commonly this also implies clientside rendering + SSR for at least some paths, once again without writing separate templates/code for the two.
It used to only be practical in JavaScript/compile-to-js-languages, but now with proliferation of `.wasm` support in the browser a compile-to-wasm language can be used effectively.

**Comment by chinedufn** [comment]
Thanks for opening this issue (:

Ah a very good point! Where do you think would be the best place(s) to put this definition? Also do you happen to have a better way to communicate this in mind? Wouldn't mind ditching the word isomorphic in order to better communicate the concepts here.

**Comment by qm3ster** [comment]
It is isomorphic though?
It's the same code/templates running on client and server.

**Comment by chinedufn** [comment]
Yeah for sure - but I'm finding that lots of people don't know what that means and it's leading to some confusion.

So really anything that helps to bridges that gap is fine here!

**Comment by chinedufn** [comment]
That sounds perfect! Feel free to submit a PR with your idea and I'll merge it in - otherwise no worries I'll get this done :)

**Comment by OutThisLife** [comment]
I would rename this to "universal". Isomorphic is not quite the correct word [anymore].

**Comment by alexreg** [comment]
@OutThisLife I've heard that too. Certainly not against it. That would mean @chinedufn doing a find & replace throughout all code though, and changing tags and descriptions on Github too...

**Comment by OutThisLife** [comment]
Just imagine being the first "Universal Rust framework" :unicorn:

**Comment by chinedufn** [comment]
Haha oh dear how the terms change over time..

Cool! I don't mind - whatever you all think is best here is cool by me!

**Comment by qm3ster** [comment]
@OutThisLife how did it stop being the correct word? I'm not being sarcastic, I would appreciate some links.
