### ISSUE TITLE
FYI: branding/naming clash

### ISSUE THREAD

**Issue by jacobq** [chinedufn/percy#167]
Looks like this project started in [July 2018](https://github.com/chinedufn/percy/commit/a989c0ffa2a78f0d10c8246f51c7022ca3e9dd05), which is [newer than](http://web.archive.org/web/20170921105814/https://percy.io/) the visual testing company/product of [the same name](https://percy.io/) (recently [acquired](https://www.prnewswire.com/news-releases/browserstack-acquires-percy-to-add-visual-testing-to-their-platform-301090792.html) by [BrowserStack](https://www.browserstack.com/percy)). 

I'm not affiliated with them (just know of them / have seen their product before) but thought you might want to know in case it helps avoid a copyright/trademark problem in the future.

**Comment by chinedufn** [comment]
Hey!

I'm aware that someone else uses the name. It isn't an issue at the moment, but if it becomes one in the future we'll address it.

Thanks for taking the time to give a heads up!
