### ISSUE TITLE
Put demo on heroku or equiv.

### ISSUE THREAD

**Issue by OutThisLife** [chinedufn/percy#18]
I'm willing to bet that most people don't have time to clone/run and would still love to play w/ what you've done.

https://github.com/emk/heroku-buildpack-rust

**Comment by chinedufn** [comment]
Oooo this would also be great incentive to improve the demo a bit. And help others see areas that they can make contributions.

Sounds great.

Is Heroku our only good free options here? Whatever is free/easy to automatically deploy sounds good to me.

**Comment by deamme** [comment]
@chinedufn There's also Zeit.co and their NOW service and docker. https://github.com/zeit/now-examples/tree/master/rust-http-microservice

**Comment by chinedufn** [comment]
Awesome! If you want to add the `now.json` and `Dockerfile` feel free.

Otherwise I'll have to circle back to this as right now I'm focusing on using Percy to build a "real site" and jotting down notes on everything that feels like a poor experience.

Regardless - awesome idea ( :
