### ISSUE TITLE
Spaces removed when isomorphic app is hydrated

### ISSUE THREAD

**Issue by EnderDev** [chinedufn/percy#182]
When running the isomorphic example, any spaces in text are removed (as shown below)

Hydrated
![image](https://user-images.githubusercontent.com/42723993/181995685-d3c380e7-d45e-46ce-8b11-0244ac9e75ef.png)

SSR copy (no JS)
![image](https://user-images.githubusercontent.com/42723993/181995692-986854a8-c01b-4bef-9f01-a14b527a2371.png)

Definitely want to use Percy for my website as your library seems to be the only Rust frontend library that provides a good SSR example rather than SSR being an afterthought.

Any ideas on how this can be fixed?

**Comment by chinedufn** [comment]
Hey sorry for the delay!

Was your client compiled on stable?

https://github.com/chinedufn/percy/blob/2aed65476bc4d4660c0eb2fe6c733ce96bf6aee7/README.md#stable-rust

**Comment by EnderDev** [comment]
I am on stable. Just switched to nightly + works just fine, thank you so much!

**Comment by chinedufn** [comment]
Great! If you'd like to stay on stable you can just wrap your text in quotes!

There's a plan to make this a compile time error instead of having people run into this and get confused. Sorry about that!

---

Related to https://github.com/chinedufn/percy/issues/170#issuecomment-1069115566
