### ISSUE TITLE
Is this thing dead?

### ISSUE THREAD

**Issue by KnorpelSenf** [chinedufn/percy#196]
There have not been any commits for 9 months, and there have been very few meaningful commits in the months before that.

Can I assume that you abandoned this project? If yes, consider archiving the repository.

**Comment by chinedufn** [comment]
I actively use `percy` in multiple applications with multiple contributors.
One is running in production with real users depending on it daily. Another is a fairly complex application that is still in development.

There is very little that I want to add to the library. Actually, there may be more things that I want to remove than I want to add.

---

Here are the main changes that I plan to make, eventually:

- A document explaining the philosophy behind the project. This should make it more clear why there will only ever be a very small set of features.

- Simplify `percy-router`. `axum`'s macro-free routing is inspiring.

- Replace the existing examples and add new ones. The current examples have little in common with how I currently use `percy`.

That's the bulk of it.

---

So, no, the project is not abandoned.

I'll close this out. You can re-open this issue if you have any further questions on this matter.

If you feel like something that you need is missing please open a new issue.
