### ISSUE TITLE
DOM patch (TruncateChildren) not working properly

### ISSUE THREAD

**Issue by dbrgn** [chinedufn/percy#48]
The `TruncateChildren` patch does not always seem to work properly when dealing with text nodes.

Test to trigger the problem:

```diff
diff --git a/crates/virtual-dom-rs/tests/diff_patch.rs b/crates/virtual-dom-rs/tests/diff_patch.rs
index d961d15..e44bc06 100644
--- a/crates/virtual-dom-rs/tests/diff_patch.rs
+++ b/crates/virtual-dom-rs/tests/diff_patch.rs
@@ -10,6 +10,10 @@ extern crate virtual_dom_rs;
 
 wasm_bindgen_test_configure!(run_in_browser);
 
+/// A diff and patch test.
+///
+/// Note: Make sure that both the old and new DOM element contain a root node
+/// with the `id` attribute set!
 struct DiffPatchTest {
     old: VirtualNode,
     new: VirtualNode,
@@ -51,6 +55,25 @@ fn truncate_children() {
     .test();
 }
 
+#[wasm_bindgen_test]
+fn truncate_children_2() {
+    DiffPatchTest {
+        old: html! {
+         <div id="old2",>
+           {"ab"} <p></p> {"c"}
+         </div>
+        },
+        new: html! {
+         <div id="new2",>
+           {"ab"} <p></p>
+         </div>
+        },
+        desc: "Truncates extra children",
+        override_expected: None,
+    }
+    .test();
+}
+
 #[wasm_bindgen_test]
 fn remove_attributes() {
     DiffPatchTest {
```

This test fails:

```
    error output:
        panicked at 'assertion failed: `(left == right)`
          left: `"<div id=\"new2\">ab<p></p>c</div>"`,
         right: `"<div id=\"new2\">ab<p></p></div>"`: Truncates extra children', crates/virtual-dom-rs/tests/diff_patch.rs:194:9
```

(When logging the patches, the generated patchset is `[AddAttributes(0, {"id": "new2"}), TruncateChildren(0, 2)]` which looks correct to me.)

(Btw, I noticed that using the same ID in two tests breaks them. It would be good if tests would be "hygienic" in the sense that tests don't influence each other. Or at least document that behavior.)

**Comment by chinedufn** [comment]
Thanks so much for the very minimal failing test case - I'm taking a look.

> (Btw, I noticed that using the same ID in two tests breaks them. It would be good if tests would be "hygienic" in the sense that tests don't influence each other. Or at least document that behavior.)

Sorry for the hassle there - I'll fix that!

**Comment by chinedufn** [comment]
Hmm looks like we're seeing 1 child node instead of 3. Seems like text nodes don't get picked up in `.children()`

https://github.com/chinedufn/percy/blob/4458a2ab58d97adc640f1e0aa9c94d9a4f75c5b2/crates/virtual-dom-rs/src/patch.rs#L203

I'll do some googling ...

**Comment by chinedufn** [comment]
Yup that turned out to be the problem. Fixed by using `child_nodes` instead of children. Now that `web_sys` has `Deref` implementations for a lot of the DOM apis's it was a trivial switch!

Mind taking a quick lookover and I'll get it merged and deployed?

https://github.com/chinedufn/percy/pull/50/files

**Comment by dbrgn** [comment]
Yep, you have to be careful when dealing with Element vs Node :slightly_smiling_face: Text nodes are not elements.

**Comment by dbrgn** [comment]
Sorry, didn't manage to test the fix in time. I'll let you know whether it worked next week, thanks for the release!

**Comment by chinedufn** [comment]
Sounds great!

**Comment by dbrgn** [comment]
Yep, I think this seems to work now!
