### ISSUE TITLE
Using typed-html

### ISSUE THREAD

**Issue by dbrgn** [chinedufn/percy#52]
Since the current html! macro seems incomplete (see #51), what about integrating https://docs.rs/typed-html/0.1.1/typed_html/index.html instead?

The tree could be generated by walking the result of the [vdom method](https://docs.rs/typed-html/0.1.1/typed_html/index.html#render-to-a-virtual-dom).

**Comment by chinedufn** [comment]
This would certainly save time if it was that straightforwards!

My one question - would this support web_sys events? I see that `typed-html` seems to lean towards `stdweb` but I haven't read over the implementation.

I think that we want to be fully based on `web_sys` so that would be the only blocker here I think.

**Comment by dbrgn** [comment]
Hm, it does look like the events are tied to `stdweb`...

Maybe another option would be to support both `stdweb` and `web_sys` events in `typed-html` using compile flags? Ping @bodil, would this be something you'd consider?

**Comment by dbrgn** [comment]
I opened an issue at https://github.com/bodil/typed-html/issues/33.

**Comment by chinedufn** [comment]
Awesome!

**Comment by chinedufn** [comment]
I've begun working on a procedural macro that that will use the web_sys event types. Progress can be followed here https://github.com/chinedufn/percy/compare/proc-macro

I'll PR it once it hits feature parity with the current macro_rules!.

**Comment by dbrgn** [comment]
@chinedufn awesome!

**Comment by chinedufn** [comment]
Closing this in favor of https://github.com/chinedufn/percy/pull/59

I'm thinking that we can open issues one by one for specific compile time checks that we'd like to have.

Thanks so much for opening this issue!

**Comment by chinedufn** [comment]
Actually, @dbrgn mind giving #59 a quick scan?
