### ISSUE TITLE
!onclick not working but compiling

### ISSUE THREAD

**Issue by richardanaya** [chinedufn/percy#55]
For some reason this log statement in on click never gets fired even though the component is rendered:

https://github.com/richardanaya/virtual-dom-rs-counter/blob/master/src/components/counter.rs

**Comment by chinedufn** [comment]
Thanks for the bug report!

So I took a quick look at the code and I'm not seeing any log statements. Mind linking me to where you're logging?

**Comment by chinedufn** [comment]
So I'm not sure what happened here, but I've made some changes to the event system and updated the examples

https://github.com/chinedufn/percy/commit/ab4e8c31e3c7bb168b7cd92bb5081efc900cb037

Closing this, feel free to re-open if you continue to see issues!
