### ISSUE TITLE
Issues with input tag

### ISSUE THREAD

**Issue by richardanaya** [chinedufn/percy#56]
I had difficulty writing:

```
<input type="button",>
{"+"}
</input>
```
however this worked just fine
```
<div type="button",>
{"+"}
</div>
```

inside the DOM it seemed to prematurely close the input tag `<input type="button"/>+`

**Comment by chinedufn** [comment]
I'm not sure if it's valid for `input` to have a child element.

I think you might want `<input type="button", value="+",></input>`

Let me know if that doesn't work for you!
