### ISSUE TITLE
VElement: props vs attributes

### ISSUE THREAD

**Issue by dbrgn** [chinedufn/percy#77]
The HTML element attributes in a `VElement` are stored in a field called `props`.

Why `props` and not `attrs` or `attributes`? If there's no particular reason behind this I'd suggest a rename to `attributes` to [match the DOM](https://developer.mozilla.org/en-US/docs/Web/API/Element/attributes).

(I suspect it was simply copied over from the JS tutorial on which the virtual dom implementation was based on.)

**Comment by chinedufn** [comment]
Yup you guessed it - `attributes` sounds like the way to go here

**Comment by chinedufn** [comment]
Or hmm maybe attrs to keep it shorter ..?

**Comment by dbrgn** [comment]
I don't really mind, but I could imagine that using the same name as in the DOM could reduce confusion. (Otherwise you have stuff like `dom_node.attributes = vdom_node.attrs` which looks a bit strange.)

**Comment by chinedufn** [comment]
Hmm since they are different types I don't think anything like `dom_node.attributes = vdom_node.attrs` would ever really happen, unless I'm missing something.

But yeah minor details 👍
