### ISSUE TITLE
Allow closures with any amount of arguments

### ISSUE THREAD

**Issue by chinedufn** [chinedufn/percy#81]
Right now if you don't provide an argument to an event callback you see this error

```
  error[E0593]: closure is expected to take 1 argument, but it takes 0 arguments
    --> examples/browser/src/lib.rs:21:20
     |
  21 |       let end_view = html! {
     |  ____________________^
  22 | |        <div class="big blue">
  23 | |           <strong>Hello, World!</strong>
  24 | |
  ...  |
  27 | |             onclick=|| {
     | |                     -- takes 0 arguments
  ...  |
  33 | |        </div>
  34 | |     };
     | |_____^ expected closure that takes 1 argument
     |
     = note: required for the cast to the object type `dyn std::ops::FnMut(_)`
  help: consider changing the closure to take and ignore the expected argument
     |
  27 |             onclick=|_| {
     |                     ^^^

  error: aborting due to previous error
```

To fix this we need to use this line https://github.com/chinedufn/percy/blob/ad82711fbfb56a7c1486deb70abb27cbb3e4667a/crates/html-macro/src/parser.rs#L79

in order to dynamically generate the number of underscores on this line

https://github.com/chinedufn/percy/blob/ad82711fbfb56a7c1486deb70abb27cbb3e4667a/crates/html-macro/src/parser.rs#L85

Something like this should work:

```rust
let underscores: Vec<TokenStream> = (0..arg_count).map(|| { quote! { _ } }).collect();

...

Box::new(#value) as Box<FnMut( #(#underscores),*)>
```

---

Along with a unit test right under here that's basically the same thing but with no parameter defined for the closure

https://github.com/chinedufn/percy/blob/ad82711fbfb56a7c1486deb70abb27cbb3e4667a/crates/html-macro-test/src/lib.rs#L45-L56

**Comment by sepiropht** [comment]
Can i take it ?

**Comment by chinedufn** [comment]
Absolutely! 

Are the above details enough? 

If not I'd be more than happy to go into more detail or answer any questions that you might have!

**Comment by sepiropht** [comment]
Thanks! I hope that it's enought

**Comment by sepiropht** [comment]
The docs is still update ? I have the last version of the repo but tests fails when i run `./test.sh`

**Comment by chinedufn** [comment]
Tests are currently failing for a couple of cases - I'll get that fixed

In the meantime you can use `cargo test -p html-macro-test` to verify that the html macro still works as expected.

Let me know if you have any issues there!

**Comment by sepiropht** [comment]
i added a test like this, and strangely it hasn't failed

```rust
fn closure_with_no_parmas() {
    HtmlMacroTest {
        desc: "No parameter defined for the closure",
        generated: html! {
            <div onclick=||{}></div>
        },
        expected: html! {<div></div>},
    }
    .test();
}

```
I'm missing something ?

**Comment by chinedufn** [comment]
Ah sorry I misled you!!!

In non wasm32 targets the html macro completely ignores closures.

https://github.com/chinedufn/percy/blob/edd4122ccee157566e5118e4c3e74d210eb3a091/crates/html-macro/src/parser/open_tag.rs#L39-L47

---

So we need to test this using our in browser tests

If you branch off of the latest master you'll see that I moved your test to `closures.rs` here -> 8c1e7a9

Very sorry for that! Let me know if there are any other stumbling blocks

**Comment by sepiropht** [comment]
I want to run closure' s tests  but this command does'nt work `wasm-pack test crates/virtual-dom-rs --chrome --headless -- --test closures`

**Comment by chinedufn** [comment]
Ahhh I'm using functionality that hasn't been released by `wasm-pack` yet.

Could you try

`cargo install --git https://github.com/rustwasm/wasm-pack` ?

**Comment by sepiropht** [comment]
Yes! It 's working !
